# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            MWC Mutants
tagline:          'A Jekyll theme'
description:      'Website for data and analysis for the MWC mutants project'
baseurl:          /

author:
  name:           'Griffin Chure'


paginate:         5


# github:
  # repo:           https://github.com/poole/hyde
